# Generated by Django 3.0.6 on 2020-07-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('is_send_email', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=254)),
                ('selected_answere', models.IntegerField(default=0)),
                ('no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.my_user')),
            ],
        ),
    ]
